# ===================================================================
# Server specific properties
# ===================================================================
server:
  port: 8080

# ===================================================================
# Spring specific properties
# ===================================================================
spring:
  application:
    name: company
  # ===================================================================
  # Data source and JPA specific properties
  # ===================================================================
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/demo}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:2202}
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      pool-name: Hikari
      auto-commit: false
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
    #   hibernate.jdbc.time_zone: UTC
    #   hibernate.id.new_generator_mappings: true
    #   hibernate.connection.provider_disables_autocommit: true
    #   hibernate.connection.autocommit: false
    #   hibernate.cache.use_second_level_cache: false
    #   hibernate.cache.use_query_cache: false
    #   hibernate.generate_statistics: false
    #   # modify batch size as necessary
    #   hibernate.jdbc.batch_size: 25
    #   hibernate.order_inserts: true
    #   hibernate.order_updates: true
    #   hibernate.query.fail_on_pagination_over_collection_fetch: true
    #   hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: update
    #   naming:
    #     physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    #     implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy


#   # ===================================================================
#   # Task execution and Scheduling specific properties
#   # ===================================================================
#   task:
#     execution:
#       thread-name-prefix: task-
#       pool:
#         core-size: 10
#         max-size: 200
#         queue-capacity: 10000
#     scheduling:
#       thread-name-prefix: scheduling-
#       pool:
#         size: 10

# logging:
#   config: classpath:log4j2.xml
#   level:
#     ROOT: INFO
#     '[net.sparkminds.company]': INFO

# management:
#   health:
#     livenessState:
#       enabled: true
#     readinessState:
#       enabled: true
#   endpoint:
#     health:
#       probes:
#         enabled: true

# app:
#   jwt:
#     secret: ${JWT_SECRET:company}
#     expiration: ${JWT_EXPIRATION:900}
#     refreshExpiration: ${JWT_REFRESH_EXPIRATION:2592000}

